openapi: 3.0.0
info:
  title: Basic Login API
  version: 1.0.0
  description: API documentation for the basic login endpoint

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /login:
    post:
      summary: Login a user
      description: Use this endpoint to authenticate a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's email address.
                  example: john@example.com
                password:
                  type: string
                  description: User's password.
                  example: mysecretpassword
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message.
                    example: Login successful.
                  user:
                    $ref: '#/components/schemas/User'
                  accessToken:
                    type: string
                    description: Access token for authenticated user.
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.
                    example: Invalid credentials.

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the user.
          example: 12345
        firstName:
          type: string
          description: User's first name.
          example: John
        lastName:
          type: string
          description: User's last name.
          example: Doe
        email:
          type: string
          description: User's email address.
          example: john@example.com
        role:
          type: string
          description: User's role (e.g., "user", "admin", etc.).
          example: user
