name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to Compute VM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          # PRIVATE_KEY: ${{ secrets.SSH_PK }}
          PRIVATE_KEY: ${{ secrets.SSH_PK_GCP }}
          # HOSTNAME: ${{secrets.SSH_HOST}}
          HOSTNAME: ${{secrets.SSH_HOST_GCP}}
          # USER_NAME: ${{secrets.SSH_USER}} 
          USER_NAME: ${{secrets.SSH_USER_GCP}} 
          CURRENT_COMMIT: ${{github.sha}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          # ssh -o StrictHostKeyChecking=no -i private_key ahmeddapo0110@theraswift.co  ' 
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@theraswift.co <<EOF
          export CURRENT_COMMIT=$CURRENT_COMMIT
              # Now we have got the access of EC2 and we will start the deployment.
              # rm -rf /home/ahmeddapo0110/repos/theraswift_backend_two 
              cd /home/ahmeddapo0110/repos/
              # gh repo clone Theraswift-Technology/theraswift_backend_two
              cd theraswift_backend_two
              git checkout main && echo Checked out CODEBASE 
              git fetch && echo UPDATED CODEBASE
              echo "latest ref"
              git rev-parse HEAD 
              git checkout ${CURRENT_COMMIT} && echo "checked out current commit $CURRENT_COMMIT"
              echo "current ref"
              git rev-parse HEAD
              node -v
              npm i && echo INSTALLED DEPENDENCIES 
              npm run build && echo BUILT CODE 
              sudo rm -rf /var/www/api.theraswift.co/dist &&  echo  REMOVED DIST DIRECTORY 
              sudo mkdir -p /var/www/api.theraswift.co/dist &&  echo  MADE DIST DIRECTORY 
              sudo mv dist /var/www/api.theraswift.co &&  echo  MOVED BUILT CODE 
              sudo mv node_modules /var/www/api.theraswift.co/dist &&  echo MOVED DEPENDENCIES 
              sudo cp package.json /var/www/api.theraswift.co/dist &&  echo COPIED PACKAGE.JSON
              sudo cp ecosystem.config.js /var/www/api.theraswift.co/dist &&  echo COPIED ecosystem.config 
              sudo cp serverconf/default.conf /etc/nginx/sites-available/api.theraswift.co && echo Copied Server Conf
              sudo ln -fs /etc/nginx/sites-available/api.theraswift.co /etc/nginx/sites-enabled/ && echo Linked Server Conf
              cd /var/www/api.theraswift.co/dist 
              sudo cp ../.env ./
              npm start 
              sudo nginx -t
              sudo systemctl restart nginx
              exit
              EOF 