name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          # PRIVATE_KEY: ${{ secrets.SSH_PK }}
          PRIVATE_KEY: ${{ secrets.SSH_PK_GCP }}
          # HOSTNAME: ${{secrets.SSH_HOST}}
          HOSTNAME: ${{secrets.SSH_HOST_GCP}}
          # USER_NAME: ${{secrets.SSH_USER}} 
          USER_NAME: ${{secrets.SSH_USER_GCP}} 

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
 
            # Now we have got the access of EC2 and we will start the deploy .
              rm -rf /home/ahmeddapo0110/repos/theraswift_backend_two 
              cd /home/ahmeddapo0110/repos/
              gh repo clone Theraswift-Technology/theraswift_backend_two
              cd theraswift_backend_two
              git checkout main && echo UPDATED CODEBASE 
              node -v
              npm i && echo INSTALLED DEPENDENCIES 
              npm run build && echo BUILT CODE 
              sudo rm -rf /var/www/api &&  echo  REMOVED DIST DIRECTORY 
              sudo mkdir -p /var/www/api/dist &&  echo  MADE DIST DIRECTORY 
              sudo mv dist /var/www/api &&  echo  MOVED BUILT CODE 
              sudo mv node_modules /var/www/api/dist &&  echo MOVED DEPENDENCIES 
              sudo cp serverconf/default.conf /etc/nginx/conf.d/api.conf && echo Copied Server Conf
              sudo cp serverconf/default.conf /etc/nginx/sites-available/api && echo Copied Server Conf
              cd /var/www/api/dist 
              npm start 
              exit
              '
